# Generated by Django 3.2 on 2023-04-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=30, verbose_name='任务名称')),
                ('task_env', models.CharField(max_length=30, verbose_name='运行环境')),
                ('pro_title', models.CharField(max_length=30, verbose_name='项目名称')),
                ('content', models.TextField(verbose_name='请求返回数据')),
                ('status', models.SmallIntegerField(choices=[(0, '已删除'), (1, '正常')], verbose_name='状态：正常/已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_user', to='user.userinfo', verbose_name='创建人uid')),
            ],
            options={
                'verbose_name': '接口测试结果',
                'db_table': 'requestor',
            },
        ),
        migrations.CreateModel(
            name='InterfaceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_title', models.CharField(default='请输入接口名称', max_length=64, verbose_name='接口名称')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=64, verbose_name='接口')),
                ('domain', models.CharField(max_length=20, verbose_name='域名')),
                ('params', models.CharField(max_length=500, null=True, verbose_name='get请求传的参数')),
                ('data', models.CharField(max_length=500, null=True, verbose_name='post请求发送表单数据')),
                ('json', models.CharField(max_length=500, null=True, verbose_name='post请求发送json数据')),
                ('headers', models.CharField(max_length=1000, null=True, verbose_name='请求头')),
                ('status', models.SmallIntegerField(choices=[(0, '已删除'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('notes', models.TextField(null=True, verbose_name='备注')),
                ('run', models.SmallIntegerField(default=1, verbose_name='是否执行')),
                ('asserts', models.CharField(max_length=500, null=True, verbose_name='断言')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='当前接口执行之前登录的用户名')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='当前接口执行之前登录的手机号')),
                ('password', models.CharField(default=0, max_length=100, verbose_name='当前接口执行之前登录的密码')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_user', to='user.userinfo', verbose_name='创建人uid')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_user', to='user.userinfo', verbose_name='更新人uid')),
            ],
            options={
                'verbose_name': '接口记录',
                'db_table': 'interface_test',
            },
        ),
    ]
